trigger: 
 - main

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.18'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: ghcr.io/freedge/dnsflow
    command: build
    Dockerfile: Containerfile.azure
- task: Docker@2
  displayName: 'Push the image'   
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    containerRegistry: 'ghcr'
    repository: ghcr.io/freedge/dnsflow
    command: push
    Dockerfile: Containerfile.azure