apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
  name: default
  namespace: abc
spec:
  egress:
  - to:
      dnsName: "example.com"
    type: Allow
  - to:
      dnsName: "google.com"
    type: Allow
  - to:
      cidrSelector: 0.0.0.0/0
    type: Deny
